services:
  postgres:
    image: postgres:16-alpine
    container_name: telemart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: telemart
      POSTGRES_PASSWORD: telemart
      POSTGRES_DB: telemart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: telemart-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: telemart-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: telemart-meilisearch
    restart: unless-stopped
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  meilisearch_data:
